### ISSUE TITLE
evaluation metric is probably computed inaccurately

### ISSUE THREAD

**Issue by VladSkripniuk** [mankadronit/Automated-Essay--Scoring#1]
Hi Ronit, I was just playing around with your code, and noticed that you computed the metric in a bit different way, than it was done in the competition https://www.kaggle.com/c/asap-aes#evaluation. In the competition they compute QWK for each essay set separately, then apply Fisher transformation and take an average, while you computed QWK for the whole essay set. The way you did it gives value very close to 1, namely 0.96, as you said in README, but if you computed the metric the way they suggested on competition page, you would get something like 0.29. Am I getting something wrong?

**Comment by tim-hub** [comment]
a very good question.

**Comment by mankadronit** [comment]
@skripniuk Ohh yes you are right! My bad, I've removed the mention of the QWK score for now. I will update the repo after fixing how I calculate the score and change the model architecture as well. Thanks for pointing that out!
