### ISSUE TITLE
TypeError: drop() got an unexpected keyword argument 'columns'

### ISSUE THREAD

**Issue by olmansju** [mankadronit/Automated-Essay--Scoring#3]
**When _importing the data_ via Jupyter Notebook:** 

# Constants
DATASET_DIR = './data/'
GLOVE_DIR = './glove.6B/'
SAVE_DIR = './'

import os
import pandas as pd

X = pd.read_csv(os.path.join(DATASET_DIR, 'training_set_rel3.tsv'), sep='\t', encoding='ISO-8859-1')
y = X['domain1_score']
X = X.dropna(axis=1)
X = X.drop(columns=['rater1_domain1', 'rater2_domain1'])

**I get:** 

TypeError                                 Traceback (most recent call last)
<ipython-input-1-240efae819cc> in <module>()
     10 y = X['domain1_score']
     11 X = X.dropna(axis=1)
---> 12 X = X.drop(columns=['rater1_domain1', 'rater2_domain1'])

TypeError: drop() got an unexpected keyword argument 'columns'

**Thoughts and suggestions welcome**

**Comment by mankadronit** [comment]
@olmansju Check your Pandas version. The **columns**  keyword was added with Pandas `0.21`. Use `pip install pandas --upgrade` if you are using pip or `conda update pandas` if you are using anaconda to update your pandas version.
