### ISSUE TITLE
replace sklearn.cross_validation with sklearn.model_selection

### ISSUE THREAD

**Issue by TcPaulyue** [mankadronit/Automated-Essay--Scoring#6]
sklearn.cross_validation was out_of_date and we need to replace it with  sklearn.model_selection.
so your code can be:
```
cv = KFold(n_splits=5,shuffle=True)
...
for traincv, testcv in cv.split(X)
...
```

**Comment by GabrielLin** [comment]
Yes.

**Comment by pds153** [comment]
Were anyone of you able to run this model and django application too? If yes could you please share your email id because i needed help for my final year project.
